#! /opt/anaconda3/envs/tenpy/bin/python

import os
import threading
import multiprocessing
threads = multiprocessing.cpu_count()
print(threads)
os.environ["OMP_NUM_THREADS"] = "4"
from enz_thread_control import run

if __name__ == "__main__":
    with multiprocessing.Manager() as manager:
        data = []
        locks = {}
        for N in [20]:
            for uot in [0.5]:
                locks[(N, uot)] = manager.Lock()
                for k in [1.]:
                    data.append((uot, N, k))

        data = [(*d, locks) for d in data]
        with multiprocessing.Pool(8) as pool:
            pool.starmap(run, data)
