#! /opt/anaconda3/bin/python

import os
import threading
import multiprocessing
import itertools
from exact_enz import run

if __name__ == "__main__":
    nsitess = [14]
    uots = [0.5]
    nstepss = [2000]
    ias = [4.]
    inds = [-2., -1., -.5, .5, 1., 2.]
    data = []
    for nsites in nsitess:
        for uot in uots:
            for ia in ias:
                for nsteps in nstepss:
                        for ind in inds:
                            data.append((nsites, nsteps, uot, ia, ind))
    list(itertools.starmap(run, data))
    # with multiprocessing.Manager() as manager:
    #     data = []
    #     for nsites in nsitess:
    #         for uot in uots:
    #             for ia in ias:
    #                 lock = manager.Lock()
    #                 for nsteps in nstepss:
    #                         for ind in inds:
    #                             data.append((nsites, nsteps, uot, ia, ind, lock))
    #
    #     with multiprocessing.Pool(4) as pool:
    #         pool.starmap(run, data)
